### ISSUE TITLE
script to parse concept ancestry for non standard vocabularies

### ISSUE THREAD

**Issue by shanmukhasampath** [FinOMOP/ROMOPMappingTools#5]
- Script will parse through non-standard vocabularies and creates a hierarchy
- As of now script should work for
     - ICD10 and ICD10fi
     - ICD9CM and ICD9fi
     - ICD8fi
     - NCSPfi
     - VNRfi

**Comment by javier-gracia-tabuenca-tuni** [comment]
replace by #7
